zookeeper:
  image: jplock/zookeeper:3.4.5
  hostname: zookeeper

mesosmaster:
  image: mesosphere/mesos-modules-dev:0.25.0-rc1
  hostname: mesosmaster
  command: /mesos/build/bin/mesos-master.sh
  environment:
    - MESOS_QUORUM=1
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_LOG_DIR=/var/log/mesos
    - MESOS_ZK=zk://zookeeper:2181/mesos
  volumes:
    - /var/log/mesos:/var/log/mesos
  ports:
    - "5050:5050"
  links:
    - zookeeper

slave:
  build: .
  privileged: true
  links:
    - mesosmaster
    - zookeeper
    - etcd
  volumes:
    - /var/log/mesos:/var/log/mesos
  environment:
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_CONTAINERIZERS=mesos
    - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
    - MESOS_LOG_DIR=/var/log
    - MESOS_RESOURCES=ports(*):[31000-31100]
    - MESOS_MODULES=file:///calico/modules.json
    - MESOS_ISOLATION=com_mesosphere_mesos_NetworkIsolator
    - MESOS_HOOKS=com_mesosphere_mesos_NetworkHook
    - ETCD_AUTHORITY=etcd:4001
  dns:
   - 192.168.255.254

marathon:
  image: spikecurtis/marathon:network-isolation-support
  environment:
    - MARATHON_MASTER=zk://zookeeper:2181/mesos
    - MARATHON_ZK=zk://zookeeper:2181/marathon
    - MARATHON_MAX_TASKS_PER_OFFER=32
  ports:
    - "8080:8080"
  links:
    - mesosmaster
    - zookeeper

etcd:
  image: spikecurtis/single-etcd
